name: artech_ui_kit
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # restart app
  # only support android and web
  restart_app: ^1.1.0
  json_rpc_2: ^3.0.1

  sprintf: ^7.0.0
  artech_api: ^0.0.1
  csc_picker: ^0.2.6
  flutter_spinbox: ^0.13.0
  font_awesome_flutter: ^10.1.0
  flutter_settings_ui: ^2.0.1
  url_launcher: ^6.0.20
  carousel_slider: ^4.0.0
  intl_phone_number_input: ^0.7.0+2
  email_validator: ^2.0.1
  string_validator: ^1.0.0
  badges: ^3.1.1
  photo_view: ^0.14.0
  qr_code_scanner: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.4

  # Maps
  flutter_map: ^4.0.0-dev.2
  geocoding: ^2.0.1
  google_maps: ^6.0.0
  google_geocoding: ^0.2.0
  #  google_maps_webservice: ^0.0.20-nullsafety.5
  #  google_maps_flutter: ^1.0.6
  #  google_maps_flutter_web: ^0.3.2+1

  #dev tools
  device_preview_screenshot: ^1.0.0

  fluro: ^2.0.3
  pull_to_refresh_flutter3: ^2.0.1
  image_picker: ^0.8.4+9
  numberpicker: ^2.1.1
  cached_network_image: ^3.2.1
  modal_bottom_sheet: ^2.0.0
  hooks_riverpod: ^2.3.6
  datetime_picker_formfield: ^2.0.0
  flutter_datetime_picker: ^1.5.0
  flutter_share: ^2.0.0
  duration_picker: ^1.0.1

  timeago_flutter: ^3.4.0
  image_gallery_saver: ^1.7.1
  share_plus: ^4.0.6
  flutter_colorpicker: ^1.0.2
  flutter_date_pickers: ^0.4.0
  geolocator: ^9.0.2
  app_settings: ^4.1.1
  flutter_slidable: ^3.0.0
#    https://github.com/letsar/flutter_slidable.git
  flutter_pdfview: ^1.2.1
  json_annotation: ^4.4.0
  flutter_markdown: ^0.6.9
  platform: ^3.1.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.2.0
  flutter_form_builder: ^8.0.0
  form_builder_validators: ^8.6.1

dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.1.3
  intl_utils: ^2.8.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   assets:
     - assets/images/
     - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
