name: artech_core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #common
  logging: ^1.0.1
  path: ^1.8.3
  rxdart: ^0.27.3
  get_it: ^7.2.0
  uuid: ^3.0.5
  build_runner: ^2.1.4
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  #config
  global_configuration: ^2.0.0-nullsafety.1
  flutter_timezone: ^1.0.4
  timezone: ^0.9.2
  universal_platform: ^1.0.0+1

  #storage
  shared_preferences: ^2.0.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  universal_html: ^2.0.8
  flutter_secure_storage: ^8.0.0
  flutter_easyloading: ^3.0.5

  #UI
  responsive_builder: ^0.7.0
  flutter_hooks: ^0.18.5+1
  package_info_plus: ^3.1.2
  multiple_localization: ^0.3.0

  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  intl_utils: ^2.8.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
  intl: ^0.18.0
# The following section is specific to Flutter.
flutter:
    # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true